### ISSUE TITLE
nfsHttp

### ISSUE THREAD

**Issue by bottleworks** [mhum/nfs-dynamic-dns#12]
Hi.  I'm getting a:
```
can't find package nfsHttp
    while executing
"package require nfsHttp"
    (file "/usr/local/src/nfs-dynamic-dns/dns.tcl" line 5)
End of script
```
Searching on Google, I'm not even seeing a "nfsHttp" package listed anywhere.  I know this script used to work.  Any ideas?

**Comment by bottleworks** [comment]
I reinstalled it and now it works.  I did do a system upgrade on the Debian OS.  Maybe that was it.

**Comment by mhum** [comment]
Awesome. Glad to hear!

The `nfsHttp` package is internal to this project.
https://github.com/mhum/nfs-dynamic-dns/blob/15ac2041ab4df1e9eef1c2b924aabdbb66f84cbe/packages/http.tcl#L1

So it all should Just Work™ as long as `dns.tcl` is ran from inside this cloned repo vs running it by itself.
